const MOVIES = [
  {
    "id": 1,
    "title": "Please Don't Skip This New Movie (A Must Watch) - 2026 Nigerian Nollywood Hits",
    "slug": "please-don-t-skip-this-new-movie-a-must-watch-2026-nigerian-nollywood-hits",
    "youtubeId": "hQOxJskhlko",
    "youtubeUrl": "https://www.youtube.com/watch?v=hQOxJskhlko",
    "watchUrl": "https://www.youtube.com/watch?v=hQOxJskhlko",
    "poster": "https://img.youtube.com/vi/hQOxJskhlko/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/hQOxJskhlko/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/hQOxJskhlko/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 7.5,
    "genre": [
      "Drama"
    ],
    "duration": "1h 24m",
    "durationMinutes": 84,
    "durationRaw": "84 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Lizzy Gold",
      "Maurice Sam",
      "Destiny Etiko"
    ],
    "synopsis": "A must-watch emotional Nollywood drama about love, betrayal and family secrets that will keep you glued till the end.",
    "isFeatured": true,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Nolly Express TV",
    "channel": "Nolly Express TV",
    "source": "YouTube",
    "views": "1.2M views",
    "tags": [
      "nollywood",
      "drama",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "lizzy-gold"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 2,
    "title": "If We Love Again - Maurice Sam, Pearl Wats",
    "slug": "if-we-love-again-maurice-sam-pearl-wats",
    "youtubeId": "beFnJRtsCfQ",
    "youtubeUrl": "https://www.youtube.com/watch?v=beFnJRtsCfQ",
    "watchUrl": "https://www.youtube.com/watch?v=beFnJRtsCfQ",
    "poster": "https://img.youtube.com/vi/beFnJRtsCfQ/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/beFnJRtsCfQ/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/beFnJRtsCfQ/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 8.7,
    "genre": [
      "Romance"
    ],
    "duration": "1h 38m",
    "durationMinutes": 98,
    "durationRaw": "98 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Maurice Sam",
      "Pearl Wats",
      "Elochukwu Godwin"
    ],
    "synopsis": "A father proposes a contract marriage to give his special needs son a chance at happiness, but will she accept a life she never planned for?",
    "isFeatured": true,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Nollywood Premier TV",
    "channel": "Nollywood Premier TV",
    "source": "YouTube",
    "views": "9.1M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 3,
    "title": "My Husband Traded My Womb For A Private Jet - Zubby Michael, Mercy Johnson",
    "slug": "my-husband-traded-my-womb-for-a-private-jet-zubby-michael-mercy-johnson",
    "youtubeId": "U1Z5h5SATpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=U1Z5h5SATpg",
    "watchUrl": "https://www.youtube.com/watch?v=U1Z5h5SATpg",
    "poster": "https://img.youtube.com/vi/U1Z5h5SATpg/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/U1Z5h5SATpg/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/U1Z5h5SATpg/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 8.4,
    "genre": [
      "Thriller"
    ],
    "duration": "1h 52m",
    "durationMinutes": 112,
    "durationRaw": "112 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Zubby Michael",
      "Mercy Johnson Okojie"
    ],
    "synopsis": "A shocking true-life inspired story of betrayal, ritual and ambition where a husband trades his wife's womb for wealth.",
    "isFeatured": true,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Fire Nolly TV",
    "channel": "Fire Nolly TV",
    "source": "YouTube",
    "views": "6.8M views",
    "tags": [
      "nollywood",
      "thriller",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "zubby-michael"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 4,
    "title": "Till Death Do Us Part",
    "slug": "till-death-do-us-part",
    "youtubeId": "icZFfuWFnEs",
    "youtubeUrl": "https://www.youtube.com/watch?v=icZFfuWFnEs",
    "watchUrl": "https://www.youtube.com/watch?v=icZFfuWFnEs",
    "poster": "https://img.youtube.com/vi/icZFfuWFnEs/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/icZFfuWFnEs/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/icZFfuWFnEs/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 7.7,
    "genre": [
      "Romance",
      "Revenge"
    ],
    "duration": "2h 7m",
    "durationMinutes": 127,
    "durationRaw": "127 min",
    "language": "English",
    "director": "Ruth Kadiri",
    "cast": [
      "Gabriel Afolayan",
      "Medinat Jimoh"
    ],
    "synopsis": "A bestselling author and a fintech mogul's perfect marriage shatters after tragic loss, grief and hidden betrayal.",
    "isFeatured": true,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Jomedia Studio",
    "channel": "Jomedia Studio",
    "source": "YouTube",
    "views": "1.2M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "gabriel-afolayan"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 5,
    "title": "Love Me For 2 Days - Saga Adeolu, Ifeka Doris",
    "slug": "love-me-for-2-days-saga-adeolu-ifeka-doris",
    "youtubeId": "xmMiEnd7vKE",
    "youtubeUrl": "https://www.youtube.com/watch?v=xmMiEnd7vKE",
    "watchUrl": "https://www.youtube.com/watch?v=xmMiEnd7vKE",
    "poster": "https://img.youtube.com/vi/xmMiEnd7vKE/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/xmMiEnd7vKE/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/xmMiEnd7vKE/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.4,
    "genre": [
      "Romance"
    ],
    "duration": "1h 24m",
    "durationMinutes": 84,
    "durationRaw": "84 min",
    "language": "English",
    "director": "Ruth Kadiri",
    "cast": [
      "Saga Adeolu",
      "Ifeka Doris"
    ],
    "synopsis": "A mysterious agreement forces two strangers to share just 48 hours but those two days change everything.",
    "isFeatured": true,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Premium Nollywood Movies",
    "channel": "Premium Nollywood Movies",
    "source": "YouTube",
    "views": "6.8M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "saga-adeolu"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 6,
    "title": "To Make You Feel - Toyin Abraham, Zubby Michael, Efe Irele",
    "slug": "to-make-you-feel-toyin-abraham-zubby-michael-efe-irele",
    "youtubeId": "rY9KWc33Kuk",
    "youtubeUrl": "https://www.youtube.com/watch?v=rY9KWc33Kuk",
    "watchUrl": "https://www.youtube.com/watch?v=rY9KWc33Kuk",
    "poster": "https://img.youtube.com/vi/rY9KWc33Kuk/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/rY9KWc33Kuk/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/rY9KWc33Kuk/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.5,
    "genre": [
      "Comedy Drama",
      "Epic"
    ],
    "duration": "1h 18m",
    "durationMinutes": 78,
    "durationRaw": "78 min",
    "language": "English",
    "director": "Lancelot Oduwa Imasuen",
    "cast": [
      "Toyin Abraham",
      "Zubby Michael",
      "Efe Irele",
      "Fausat Balogun"
    ],
    "synopsis": "A couple tries to save their marriage by cheating with younger lovers, leading to hilarious and chaotic consequences.",
    "isFeatured": true,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Toyin Abraham TV",
    "channel": "Toyin Abraham TV",
    "source": "YouTube",
    "views": "6.8M views",
    "tags": [
      "nollywood",
      "comedy drama",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "toyin-abraham"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 7,
    "title": "Critical Love Story - Maurice Sam, Uche Montana, Chioma Nwaoha",
    "slug": "critical-love-story-maurice-sam-uche-montana-chioma-nwaoha",
    "youtubeId": "h5Mk2SaoJHo",
    "youtubeUrl": "https://www.youtube.com/watch?v=h5Mk2SaoJHo",
    "watchUrl": "https://www.youtube.com/watch?v=h5Mk2SaoJHo",
    "poster": "https://img.youtube.com/vi/h5Mk2SaoJHo/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/h5Mk2SaoJHo/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/h5Mk2SaoJHo/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.5,
    "genre": [
      "Romance"
    ],
    "duration": "2h 15m",
    "durationMinutes": 135,
    "durationRaw": "135 min",
    "language": "English",
    "director": "Moses Inwang",
    "cast": [
      "Maurice Sam",
      "Uche Montana",
      "Chioma Nwaoha",
      "Chinenye Nnebe"
    ],
    "synopsis": "A dangerous side chick threatens a blossoming love story in this critical tale of love, trust and betrayal.",
    "isFeatured": true,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Felix Okeke Movies TV",
    "channel": "Felix Okeke Movies TV",
    "source": "YouTube",
    "views": "3.1M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 8,
    "title": "BEYOND ACCESS (2025)",
    "slug": "beyond-access-2025",
    "youtubeId": "QsgxCoUCZBM",
    "poster": "https://img.youtube.com/vi/QsgxCoUCZBM/hqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/QsgxCoUCZBM/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": "PG-13",
    "genre": [
      "Drama",
      "Romance"
    ],
    "duration": "2h 3m",
    "durationMinutes": 123,
    "durationRaw": "PT2H3M2S",
    "language": "English",
    "director": "Uche Nancy",
    "cast": [
      "Chinenye Nnebe",
      "Deza the Great",
      "Sophia Alakija",
      "Oma Nnadi"
    ],
    "synopsis": "Beyond Access explores the complexities of modern relationships through the lens of a demanding career. A couple navigates work-life balance, household chores, and intimacy, revealing underlying tensions. The arrival of a new house help further complicates their dynamic.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "source": "Uche Nancy TV",
    "channel": "Uche Nancy TV",
    "views": 0,
    "tags": [
      "nollywood",
      "nigerian movie",
      "2025 movie",
      "uche nancy tv",
      "chinenye nnebe",
      "deza the great",
      "sophia alakija",
      "oma nnadi",
      "drama",
      "romance",
      "full movie"
    ]
  },
  {
    "id": 9,
    "title": "Two Hearts - Maurice Sam, Uche Montana, Clinton Joshua",
    "slug": "two-hearts-maurice-sam-uche-montana-clinton-joshua",
    "youtubeId": "vw75EETCL7E",
    "youtubeUrl": "https://www.youtube.com/watch?v=vw75EETCL7E",
    "watchUrl": "https://www.youtube.com/watch?v=vw75EETCL7E",
    "poster": "https://img.youtube.com/vi/vw75EETCL7E/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/vw75EETCL7E/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/vw75EETCL7E/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.9,
    "genre": [
      "Romance"
    ],
    "duration": "2h 22m",
    "durationMinutes": 142,
    "durationRaw": "142 min",
    "language": "English",
    "director": "Ruth Kadiri",
    "cast": [
      "Maurice Sam",
      "Uche Montana",
      "Clinton Joshua"
    ],
    "synopsis": "Two hearts collide when love, ambition and secrets force difficult choices.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Best of Nollywood Movies",
    "channel": "Best of Nollywood Movies",
    "source": "YouTube",
    "views": "4.5M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 10,
    "title": "Stolen Hearts - Maurice Sam, Uche Montana",
    "slug": "stolen-hearts-maurice-sam-uche-montana",
    "youtubeId": "VK1ZJnmbpbw",
    "youtubeUrl": "https://www.youtube.com/watch?v=VK1ZJnmbpbw",
    "watchUrl": "https://www.youtube.com/watch?v=VK1ZJnmbpbw",
    "poster": "https://img.youtube.com/vi/VK1ZJnmbpbw/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/VK1ZJnmbpbw/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/VK1ZJnmbpbw/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 8.0,
    "genre": [
      "Drama"
    ],
    "duration": "1h 24m",
    "durationMinutes": 84,
    "durationRaw": "84 min",
    "language": "English",
    "director": "Omoni Oboli",
    "cast": [
      "Maurice Sam",
      "Uche Montana",
      "Crystal Okoye"
    ],
    "synopsis": "Stuck in a toxic relationship, she finds courage to leave when she meets someone who shows her what love should feel like.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Ivory Nolly TV",
    "channel": "Ivory Nolly TV",
    "source": "YouTube",
    "views": "3.1M views",
    "tags": [
      "nollywood",
      "drama",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 11,
    "title": "Drunk In Love - Maurice Sam, Uche Montana",
    "slug": "drunk-in-love-maurice-sam-uche-montana",
    "youtubeId": "tf3nLfhV9UY",
    "youtubeUrl": "https://www.youtube.com/watch?v=tf3nLfhV9UY",
    "watchUrl": "https://www.youtube.com/watch?v=tf3nLfhV9UY",
    "poster": "https://img.youtube.com/vi/tf3nLfhV9UY/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/tf3nLfhV9UY/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/tf3nLfhV9UY/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.1,
    "genre": [
      "Romance",
      "Campus"
    ],
    "duration": "1h 58m",
    "durationMinutes": 118,
    "durationRaw": "118 min",
    "language": "English",
    "director": "Lancelot Oduwa Imasuen",
    "cast": [
      "Maurice Sam",
      "Uche Montana"
    ],
    "synopsis": "A wild night leads to unexpected love between two strangers from different worlds.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Exclusive Nollywood Movies",
    "channel": "Exclusive Nollywood Movies",
    "source": "YouTube",
    "views": "3.1M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 12,
    "title": "I Believe In You - Maurice Sam, Sonia Uche",
    "slug": "i-believe-in-you-maurice-sam-sonia-uche",
    "youtubeId": "njQUfZ1WaF8",
    "youtubeUrl": "https://www.youtube.com/watch?v=njQUfZ1WaF8",
    "watchUrl": "https://www.youtube.com/watch?v=njQUfZ1WaF8",
    "poster": "https://img.youtube.com/vi/njQUfZ1WaF8/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/njQUfZ1WaF8/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/njQUfZ1WaF8/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 8.6,
    "genre": [
      "Romance",
      "Crime"
    ],
    "duration": "1h 18m",
    "durationMinutes": 78,
    "durationRaw": "78 min",
    "language": "English",
    "director": "Omoni Oboli",
    "cast": [
      "Maurice Sam",
      "Sonia Uche"
    ],
    "synopsis": "When everyone doubts her, one man believes in her dreams and love blossoms against all odds.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Prime Movies TV",
    "channel": "Prime Movies TV",
    "source": "YouTube",
    "views": "4.5M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 13,
    "title": "Poor Orphan Never Knew The Poor Village Boy She Loved Was A Billionaire Prince",
    "slug": "poor-orphan-never-knew-the-poor-village-boy-she-loved-was-a-billionaire-prince",
    "youtubeId": "0BTyT-NE2I0",
    "youtubeUrl": "https://www.youtube.com/watch?v=0BTyT-NE2I0",
    "watchUrl": "https://www.youtube.com/watch?v=0BTyT-NE2I0",
    "poster": "https://img.youtube.com/vi/0BTyT-NE2I0/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/0BTyT-NE2I0/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/0BTyT-NE2I0/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.7,
    "genre": [
      "Royal Drama"
    ],
    "duration": "1h 58m",
    "durationMinutes": 118,
    "durationRaw": "118 min",
    "language": "English, Igbo",
    "director": "Moses Inwang",
    "cast": [
      "Destiny Etiko",
      "Zubby Michael"
    ],
    "synopsis": "A humble orphan finds love with a village boy who is secretly a billionaire prince searching for a true wife.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Movie Lane",
    "channel": "Movie Lane",
    "source": "YouTube",
    "views": "9.1M views",
    "tags": [
      "nollywood",
      "royal drama",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "destiny-etiko"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 14,
    "title": "All Of Me - 2026 Nigerian Nollywood African Movie",
    "slug": "all-of-me-2026-nigerian-nollywood-african-movie",
    "youtubeId": "ODVFXZt8bE0",
    "youtubeUrl": "https://www.youtube.com/watch?v=ODVFXZt8bE0",
    "watchUrl": "https://www.youtube.com/watch?v=ODVFXZt8bE0",
    "poster": "https://img.youtube.com/vi/ODVFXZt8bE0/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/ODVFXZt8bE0/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/ODVFXZt8bE0/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 8.6,
    "genre": [
      "Drama"
    ],
    "duration": "1h 58m",
    "durationMinutes": 118,
    "durationRaw": "118 min",
    "language": "English",
    "director": "Moses Inwang",
    "cast": [
      "Destiny Etiko",
      "Mike Godson"
    ],
    "synopsis": "Every lady needs to watch this emotional story of sacrifice, love and resilience.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Nolly Express TV",
    "channel": "Nolly Express TV",
    "source": "YouTube",
    "views": "9.1M views",
    "tags": [
      "nollywood",
      "drama",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "destiny-etiko"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 15,
    "title": "Lagos Big Girls - Uche Montana, Bimbo Ademoye",
    "slug": "lagos-big-girls-uche-montana-bimbo-ademoye",
    "youtubeId": "A542icbwRxc",
    "youtubeUrl": "https://www.youtube.com/watch?v=A542icbwRxc",
    "watchUrl": "https://www.youtube.com/watch?v=A542icbwRxc",
    "poster": "https://img.youtube.com/vi/A542icbwRxc/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/A542icbwRxc/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/A542icbwRxc/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 8.6,
    "genre": [
      "Drama",
      "Epic"
    ],
    "duration": "2h 7m",
    "durationMinutes": 127,
    "durationRaw": "127 min",
    "language": "English",
    "director": "Moses Inwang",
    "cast": [
      "Uche Montana",
      "Bimbo Ademoye",
      "Chioma Nwaoha",
      "Onyii Alex"
    ],
    "synopsis": "Four glamorous Lagos women chase luxury, love and fame, but hidden secrets threaten to destroy their friendship.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Premium Bumaks TV",
    "channel": "Premium Bumaks TV",
    "source": "YouTube",
    "views": "9.1M views",
    "tags": [
      "nollywood",
      "drama",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "uche-montana"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 16,
    "title": "The Perfect Match - Bimbo Ademoye, Timini Egbuson",
    "slug": "the-perfect-match-bimbo-ademoye-timini-egbuson",
    "youtubeId": "riUvGGk7FDk",
    "youtubeUrl": "https://www.youtube.com/watch?v=riUvGGk7FDk",
    "watchUrl": "https://www.youtube.com/watch?v=riUvGGk7FDk",
    "poster": "https://img.youtube.com/vi/riUvGGk7FDk/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/riUvGGk7FDk/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/riUvGGk7FDk/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.6,
    "genre": [
      "Romantic Comedy"
    ],
    "duration": "1h 41m",
    "durationMinutes": 101,
    "durationRaw": "101 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Bimbo Ademoye",
      "Timini Egbuson",
      "Oluebube Obio"
    ],
    "synopsis": "A young woman navigating online dating finds unexpected romance in this hilarious and heartwarming comedy.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Bimbo Ademoye TV",
    "channel": "Bimbo Ademoye TV",
    "source": "YouTube",
    "views": "6.8M views",
    "tags": [
      "nollywood",
      "romantic comedy",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "bimbo-ademoye"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 17,
    "title": "Night Runs - Bimbo Ademoye, Timini Egbuson",
    "slug": "night-runs-bimbo-ademoye-timini-egbuson",
    "youtubeId": "yauL4wGcTx0",
    "youtubeUrl": "https://www.youtube.com/watch?v=yauL4wGcTx0",
    "watchUrl": "https://www.youtube.com/watch?v=yauL4wGcTx0",
    "poster": "https://img.youtube.com/vi/yauL4wGcTx0/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/yauL4wGcTx0/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/yauL4wGcTx0/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 7.9,
    "genre": [
      "Romance"
    ],
    "duration": "2h 2m",
    "durationMinutes": 122,
    "durationRaw": "122 min",
    "language": "English",
    "director": "Ruth Kadiri",
    "cast": [
      "Bimbo Ademoye",
      "Timini Egbuson"
    ],
    "synopsis": "Two strangers escape troubled lives through nightly drives, but secrets surface and freedom turns into love.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "21st Century Nollywood",
    "channel": "21st Century Nollywood",
    "source": "YouTube",
    "views": "2.3M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "bimbo-ademoye"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 18,
    "title": "Love In Chaos - Ruth Kadiri, Michael Dappa, Deza The Great",
    "slug": "love-in-chaos-ruth-kadiri-michael-dappa-deza-the-great",
    "youtubeId": "UbSknikE2sI",
    "youtubeUrl": "https://www.youtube.com/watch?v=UbSknikE2sI",
    "watchUrl": "https://www.youtube.com/watch?v=UbSknikE2sI",
    "poster": "https://img.youtube.com/vi/UbSknikE2sI/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/UbSknikE2sI/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/UbSknikE2sI/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 8.5,
    "genre": [
      "Drama",
      "Crime"
    ],
    "duration": "1h 32m",
    "durationMinutes": 92,
    "durationRaw": "92 min",
    "language": "English",
    "director": "Lancelot Oduwa Imasuen",
    "cast": [
      "Ruth Kadiri",
      "Michael Dappa",
      "Deza The Great"
    ],
    "synopsis": "Heartbreak, family struggles and unexpected romance collide when life falls apart and love becomes the only hope.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "RuthKadiri247",
    "channel": "RuthKadiri247",
    "source": "YouTube",
    "views": "9.1M views",
    "tags": [
      "nollywood",
      "drama",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "ruth-kadiri"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 19,
    "title": "The Married Lover - Ruth Kadiri, Uzor Arukwe, Bam Bam",
    "slug": "the-married-lover-ruth-kadiri-uzor-arukwe-bam-bam",
    "youtubeId": "Wj-RIj_M22k",
    "youtubeUrl": "https://www.youtube.com/watch?v=Wj-RIj_M22k",
    "watchUrl": "https://www.youtube.com/watch?v=Wj-RIj_M22k",
    "poster": "https://img.youtube.com/vi/Wj-RIj_M22k/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/Wj-RIj_M22k/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/Wj-RIj_M22k/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 7.0,
    "genre": [
      "Drama"
    ],
    "duration": "2h 15m",
    "durationMinutes": 135,
    "durationRaw": "135 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Ruth Kadiri",
      "Uzor Arukwe",
      "Bamike Olawunmi"
    ],
    "synopsis": "A charming man risks everything for forbidden love with married women until scandal threatens to destroy all.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "21st Century Nollywood",
    "channel": "21st Century Nollywood",
    "source": "YouTube",
    "views": "5.2M views",
    "tags": [
      "nollywood",
      "drama",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "ruth-kadiri"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 20,
    "title": "Must Be Yours - Ruth Kadiri, Eso Dike, Shaznay Okawa",
    "slug": "must-be-yours-ruth-kadiri-eso-dike-shaznay-okawa",
    "youtubeId": "HU61n4pgrN4",
    "youtubeUrl": "https://www.youtube.com/watch?v=HU61n4pgrN4",
    "watchUrl": "https://www.youtube.com/watch?v=HU61n4pgrN4",
    "poster": "https://img.youtube.com/vi/HU61n4pgrN4/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/HU61n4pgrN4/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/HU61n4pgrN4/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 7.1,
    "genre": [
      "Romance Thriller"
    ],
    "duration": "1h 58m",
    "durationMinutes": 118,
    "durationRaw": "118 min",
    "language": "English",
    "director": "Uche Nancy",
    "cast": [
      "Ruth Kadiri",
      "Eso Dike",
      "Shaznay Okawa"
    ],
    "synopsis": "A man torn between two obsessive women discovers jealousy and betrayal can turn love into a dangerous game.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "21st Century Nollywood",
    "channel": "21st Century Nollywood",
    "source": "YouTube",
    "views": "1.2M views",
    "tags": [
      "nollywood",
      "romance thriller",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "ruth-kadiri"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 21,
    "title": "When Love Moved In - Maurice Sam, Ruth Kadiri, Chioma Nwaoha",
    "slug": "when-love-moved-in-maurice-sam-ruth-kadiri-chioma-nwaoha",
    "youtubeId": "vRhC8mfXPNE",
    "youtubeUrl": "https://www.youtube.com/watch?v=vRhC8mfXPNE",
    "watchUrl": "https://www.youtube.com/watch?v=vRhC8mfXPNE",
    "poster": "https://img.youtube.com/vi/vRhC8mfXPNE/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/vRhC8mfXPNE/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/vRhC8mfXPNE/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 8.3,
    "genre": [
      "Romance",
      "Faith"
    ],
    "duration": "2h 15m",
    "durationMinutes": 135,
    "durationRaw": "135 min",
    "language": "English",
    "director": "Lancelot Oduwa Imasuen",
    "cast": [
      "Maurice Sam",
      "Ruth Kadiri",
      "Chioma Nwaoha"
    ],
    "synopsis": "Love moves in unexpectedly and turns three lives upside down in this emotional Nollywood hit.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Felix Okeke Movies TV",
    "channel": "Felix Okeke Movies TV",
    "source": "YouTube",
    "views": "6.8M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 22,
    "title": "Mr Perfect - Timini Egbuson, Bimbo Ademoye",
    "slug": "mr-perfect-timini-egbuson-bimbo-ademoye",
    "youtubeId": "9bWVWLeV6yc",
    "youtubeUrl": "https://www.youtube.com/watch?v=9bWVWLeV6yc",
    "watchUrl": "https://www.youtube.com/watch?v=9bWVWLeV6yc",
    "poster": "https://img.youtube.com/vi/9bWVWLeV6yc/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/9bWVWLeV6yc/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/9bWVWLeV6yc/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.8,
    "genre": [
      "Romance"
    ],
    "duration": "2h 22m",
    "durationMinutes": 142,
    "durationRaw": "142 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Timini Egbuson",
      "Bimbo Ademoye"
    ],
    "synopsis": "A poor waitress meets a charming rich man but her fairytale shatters when she discovers he is already married.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Nollyhub Studio",
    "channel": "Nollyhub Studio",
    "source": "YouTube",
    "views": "3.1M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "timini-egbuson"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 23,
    "title": "The Brotherhood - Yul Edochie, Lizzy Gold",
    "slug": "the-brotherhood-yul-edochie-lizzy-gold",
    "youtubeId": "3KPdro3NxHk",
    "youtubeUrl": "https://www.youtube.com/watch?v=3KPdro3NxHk",
    "watchUrl": "https://www.youtube.com/watch?v=3KPdro3NxHk",
    "poster": "https://img.youtube.com/vi/3KPdro3NxHk/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/3KPdro3NxHk/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/3KPdro3NxHk/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 7.6,
    "genre": [
      "Epic"
    ],
    "duration": "2h 2m",
    "durationMinutes": 122,
    "durationRaw": "122 min",
    "language": "English, Igbo",
    "director": "Omoni Oboli",
    "cast": [
      "Yul Edochie",
      "Lizzy Gold Onuwaje",
      "Emmanuel Okhakhu"
    ],
    "synopsis": "Ichie's spirit remains trapped as his cult demands a son's loyalty. Chekwube must fight darkness to reclaim his father's soul.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Nollywood Premier TV",
    "channel": "Nollywood Premier TV",
    "source": "YouTube",
    "views": "9.1M views",
    "tags": [
      "nollywood",
      "epic",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "yul-edochie"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 24,
    "title": "THE STRANGE WOMAN",
    "slug": "the-strange-woman-2026",
    "youtubeId": "MCJk0fudJao",
    "poster": "https://img.youtube.com/vi/MCJk0fudJao/hqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/MCJk0fudJao/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": "PG-13",
    "genre": [
      "Thriller",
      "Drama",
      "Mystery",
      "Romance"
    ],
    "duration": "1h 42m",
    "durationMinutes": 102,
    "durationRaw": "PT1H42M",
    "language": "English",
    "director": "Maurice Sam",
    "cast": [
      "Maurice Sam",
      "Sophie Alakija",
      "Emem Udonquak"
    ],
    "synopsis": "THE STRANGE WOMAN is a gripping story filled with mystery, love, betrayal, shocking secrets, and unexpected twists that will keep you watching until the very end.",
    "isFeatured": true,
    "verifiedReal": true,
    "hasTrailer": false,
    "source": "Maurice Sam TV",
    "channel": "Maurice Sam TV",
    "views": null,
    "tags": [
      "nollywood",
      "nigerian movie",
      "2026",
      "maurice sam tv",
      "maurice sam",
      "sophie alakija",
      "emem udonquak",
      "thriller",
      "mystery",
      "love",
      "betrayal"
    ]
  },
  {
    "id": 25,
    "title": "Two Hearts Apart - Bimbo Ademoye, Timini Egbuson",
    "slug": "two-hearts-apart-bimbo-ademoye-timini-egbuson",
    "youtubeId": "cIxqUthYYCA",
    "youtubeUrl": "https://www.youtube.com/watch?v=cIxqUthYYCA",
    "watchUrl": "https://www.youtube.com/watch?v=cIxqUthYYCA",
    "poster": "https://img.youtube.com/vi/cIxqUthYYCA/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/cIxqUthYYCA/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/cIxqUthYYCA/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 7.2,
    "genre": [
      "Drama"
    ],
    "duration": "1h 52m",
    "durationMinutes": 112,
    "durationRaw": "112 min",
    "language": "English",
    "director": "Omoni Oboli",
    "cast": [
      "Bimbo Ademoye",
      "Kunle Remi",
      "Melvin Oduah"
    ],
    "synopsis": "A self-made woman who gets everything she wants tastes rejection for the first time when Sylvester comes along.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Sommy Nolly TV",
    "channel": "Sommy Nolly TV",
    "source": "YouTube",
    "views": "0.8M views",
    "tags": [
      "nollywood",
      "drama",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "bimbo-ademoye"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 26,
    "title": "King Of Malice - Yul Edochie, Lizzy Gold",
    "slug": "king-of-malice-yul-edochie-lizzy-gold",
    "youtubeId": "lCQsoeKDDF8",
    "youtubeUrl": "https://www.youtube.com/watch?v=lCQsoeKDDF8",
    "watchUrl": "https://www.youtube.com/watch?v=lCQsoeKDDF8",
    "poster": "https://img.youtube.com/vi/lCQsoeKDDF8/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/lCQsoeKDDF8/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/lCQsoeKDDF8/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 7.1,
    "genre": [
      "Royal Drama"
    ],
    "duration": "1h 18m",
    "durationMinutes": 78,
    "durationRaw": "78 min",
    "language": "English, Igbo",
    "director": "Emem Isong",
    "cast": [
      "Yul Edochie",
      "Lizzy Gold"
    ],
    "synopsis": "A throne built on lies crumbles when hidden enemies rise within the palace.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Nollywood Premium Channel",
    "channel": "Nollywood Premium Channel",
    "source": "YouTube",
    "views": "6.8M views",
    "tags": [
      "nollywood",
      "royal drama",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "yul-edochie"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 27,
    "title": "Dark Money - Yul Edochie, Lizzy Gold",
    "slug": "dark-money-yul-edochie-lizzy-gold",
    "youtubeId": "LlhW6NQLA2c",
    "youtubeUrl": "https://www.youtube.com/watch?v=LlhW6NQLA2c",
    "watchUrl": "https://www.youtube.com/watch?v=LlhW6NQLA2c",
    "poster": "https://img.youtube.com/vi/LlhW6NQLA2c/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/LlhW6NQLA2c/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/LlhW6NQLA2c/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 8.7,
    "genre": [
      "Ritual Thriller",
      "Epic"
    ],
    "duration": "2h 2m",
    "durationMinutes": 122,
    "durationRaw": "122 min",
    "language": "English",
    "director": "Omoni Oboli",
    "cast": [
      "Yul Edochie",
      "Lizzy Gold Onuwaje"
    ],
    "synopsis": "A father's burial is held hostage by a cult that demands one son join them, forcing a battle between light and darkness.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Exclusive TV Plus",
    "channel": "Exclusive TV Plus",
    "source": "YouTube",
    "views": "2.3M views",
    "tags": [
      "nollywood",
      "ritual thriller",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "yul-edochie"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 28,
    "title": "Crazy Manhood - Maurice Sam, Ekene Umenwa, Sonia Uche",
    "slug": "crazy-manhood-maurice-sam-ekene-umenwa-sonia-uche",
    "youtubeId": "0Z0sjtQ8qiU",
    "youtubeUrl": "https://www.youtube.com/watch?v=0Z0sjtQ8qiU",
    "watchUrl": "https://www.youtube.com/watch?v=0Z0sjtQ8qiU",
    "poster": "https://img.youtube.com/vi/0Z0sjtQ8qiU/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/0Z0sjtQ8qiU/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/0Z0sjtQ8qiU/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.3,
    "genre": [
      "Comedy",
      "Crime"
    ],
    "duration": "1h 41m",
    "durationMinutes": 101,
    "durationRaw": "101 min",
    "language": "English",
    "director": "Moses Inwang",
    "cast": [
      "Maurice Sam",
      "Ekene Umenwa",
      "Sonia Uche"
    ],
    "synopsis": "Manhood is tested in hilarious and crazy ways when love and ego clash.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Felix Okeke Movies TV",
    "channel": "Felix Okeke Movies TV",
    "source": "YouTube",
    "views": "9.1M views",
    "tags": [
      "nollywood",
      "comedy",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 29,
    "title": "In Love With A Street Girl - Maurice Sam, Sonia Uche",
    "slug": "in-love-with-a-street-girl-maurice-sam-sonia-uche",
    "youtubeId": "gbH5WHsnyak",
    "youtubeUrl": "https://www.youtube.com/watch?v=gbH5WHsnyak",
    "watchUrl": "https://www.youtube.com/watch?v=gbH5WHsnyak",
    "poster": "https://img.youtube.com/vi/gbH5WHsnyak/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/gbH5WHsnyak/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/gbH5WHsnyak/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.5,
    "genre": [
      "Romance"
    ],
    "duration": "1h 58m",
    "durationMinutes": 118,
    "durationRaw": "118 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Maurice Sam",
      "Sonia Uche"
    ],
    "synopsis": "A billionaire falls for a street girl, but society and secrets threaten their unlikely love.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "True Nolly TV",
    "channel": "True Nolly TV",
    "source": "YouTube",
    "views": "0.8M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 30,
    "title": "My Crazy Boss - Maurice Sam, Sonia Uche",
    "slug": "my-crazy-boss-maurice-sam-sonia-uche",
    "youtubeId": "DgujDvxQMD0",
    "youtubeUrl": "https://www.youtube.com/watch?v=DgujDvxQMD0",
    "watchUrl": "https://www.youtube.com/watch?v=DgujDvxQMD0",
    "poster": "https://img.youtube.com/vi/DgujDvxQMD0/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/DgujDvxQMD0/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/DgujDvxQMD0/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.5,
    "genre": [
      "Romantic Comedy"
    ],
    "duration": "1h 41m",
    "durationMinutes": 101,
    "durationRaw": "101 min",
    "language": "English",
    "director": "Ruth Kadiri",
    "cast": [
      "Maurice Sam",
      "Sonia Uche"
    ],
    "synopsis": "A strict boss and his employee find love in the most chaotic office romance.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Temple Movies TV",
    "channel": "Temple Movies TV",
    "source": "YouTube",
    "views": "6.8M views",
    "tags": [
      "nollywood",
      "romantic comedy",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 31,
    "title": "Don't Judge Me - Maurice Sam, Sonia Uche",
    "slug": "don-t-judge-me-maurice-sam-sonia-uche",
    "youtubeId": "daxLrGQcJJU",
    "youtubeUrl": "https://www.youtube.com/watch?v=daxLrGQcJJU",
    "watchUrl": "https://www.youtube.com/watch?v=daxLrGQcJJU",
    "poster": "https://img.youtube.com/vi/daxLrGQcJJU/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/daxLrGQcJJU/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/daxLrGQcJJU/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.3,
    "genre": [
      "Drama"
    ],
    "duration": "2h 22m",
    "durationMinutes": 142,
    "durationRaw": "142 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Maurice Sam",
      "Sonia Uche",
      "Kheira Hewatch"
    ],
    "synopsis": "Love, pain and redemption in a world quick to condemn. A story that teaches not to judge.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Maurice Sam TV",
    "channel": "Maurice Sam TV",
    "source": "YouTube",
    "views": "3.1M views",
    "tags": [
      "nollywood",
      "drama",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 32,
    "title": "Smash - Uzor Arukwe, Iyabo Ojo, Gideon Okeke",
    "slug": "smash-uzor-arukwe-iyabo-ojo-gideon-okeke",
    "youtubeId": "0UoNzQYrPeE",
    "youtubeUrl": "https://www.youtube.com/watch?v=0UoNzQYrPeE",
    "watchUrl": "https://www.youtube.com/watch?v=0UoNzQYrPeE",
    "poster": "https://img.youtube.com/vi/0UoNzQYrPeE/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/0UoNzQYrPeE/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/0UoNzQYrPeE/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.7,
    "genre": [
      "Comedy",
      "Action"
    ],
    "duration": "1h 58m",
    "durationMinutes": 118,
    "durationRaw": "118 min",
    "language": "English",
    "director": "Uche Nancy",
    "cast": [
      "Uzor Arukwe",
      "Iyabo Ojo",
      "Gideon Okeke",
      "Enyinna Nwigwe"
    ],
    "synopsis": "A rib-cracking comedy about drama, romance and madness when ambition meets opportunity.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Yaw Naija Entertainment",
    "channel": "Yaw Naija Entertainment",
    "source": "YouTube",
    "views": "5.2M views",
    "tags": [
      "nollywood",
      "comedy",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "uzor-arukwe"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 33,
    "title": "Shege For 2 - Kunle Remi, Teniola Aladese",
    "slug": "shege-for-2-kunle-remi-teniola-aladese",
    "youtubeId": "xh5UrIYtBlI",
    "youtubeUrl": "https://www.youtube.com/watch?v=xh5UrIYtBlI",
    "watchUrl": "https://www.youtube.com/watch?v=xh5UrIYtBlI",
    "poster": "https://img.youtube.com/vi/xh5UrIYtBlI/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/xh5UrIYtBlI/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/xh5UrIYtBlI/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.8,
    "genre": [
      "Comedy Drama"
    ],
    "duration": "2h 22m",
    "durationMinutes": 142,
    "durationRaw": "142 min",
    "language": "English",
    "director": "Ruth Kadiri",
    "cast": [
      "Kunle Remi",
      "Teniola Aladese",
      "Gabriel Afolayan"
    ],
    "synopsis": "A couple is forced to walk in each other's shoes, learning empathy through hilarious chaos.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Kunle Remi TV",
    "channel": "Kunle Remi TV",
    "source": "YouTube",
    "views": "3.1M views",
    "tags": [
      "nollywood",
      "comedy drama",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "kunle-remi"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 34,
    "title": "Mend My Soul - Ekene Umenwa, Destiny Etiko",
    "slug": "mend-my-soul-ekene-umenwa-destiny-etiko",
    "youtubeId": "TKARVtkNvO0",
    "youtubeUrl": "https://www.youtube.com/watch?v=TKARVtkNvO0",
    "watchUrl": "https://www.youtube.com/watch?v=TKARVtkNvO0",
    "poster": "https://img.youtube.com/vi/TKARVtkNvO0/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/TKARVtkNvO0/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/TKARVtkNvO0/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.6,
    "genre": [
      "Royal Comedy Drama",
      "Horror"
    ],
    "duration": "1h 58m",
    "durationMinutes": 118,
    "durationRaw": "118 min",
    "language": "English, Igbo",
    "director": "Uche Nancy",
    "cast": [
      "Destiny Etiko",
      "Ekene Umenwa Ogbodo",
      "Jude Ogbodo"
    ],
    "synopsis": "After her mother's death, a princess falls into silence until a spirited nurse brings laughter and healing to the palace.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Ekene Umenwa TV",
    "channel": "Ekene Umenwa TV",
    "source": "YouTube",
    "views": "5.2M views",
    "tags": [
      "nollywood",
      "royal comedy drama",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "destiny-etiko"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 35,
    "title": "Gen Z Wife - Chioma Nwaoha, Maurice Sam",
    "slug": "gen-z-wife-chioma-nwaoha-maurice-sam",
    "youtubeId": "JDtY4nO9N8A",
    "youtubeUrl": "https://www.youtube.com/watch?v=JDtY4nO9N8A",
    "watchUrl": "https://www.youtube.com/watch?v=JDtY4nO9N8A",
    "poster": "https://img.youtube.com/vi/JDtY4nO9N8A/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/JDtY4nO9N8A/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/JDtY4nO9N8A/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.7,
    "genre": [
      "Romantic Comedy"
    ],
    "duration": "1h 32m",
    "durationMinutes": 92,
    "durationRaw": "92 min",
    "language": "English",
    "director": "Ruth Kadiri",
    "cast": [
      "Chioma Nwaoha",
      "Maurice Sam"
    ],
    "synopsis": "A Gen Z wife's modern lifestyle clashes with traditional marriage expectations in this laugh-out-loud comedy.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Gnolly TV",
    "channel": "Gnolly TV",
    "source": "YouTube",
    "views": "1.2M views",
    "tags": [
      "nollywood",
      "romantic comedy",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "chioma-nwaoha"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 36,
    "title": "Between Two Lovers - Maurice Sam, Chioma Nwaoha, Sonia Uche",
    "slug": "between-two-lovers-maurice-sam-chioma-nwaoha-sonia-uche",
    "youtubeId": "sIn5i3QemAY",
    "youtubeUrl": "https://www.youtube.com/watch?v=sIn5i3QemAY",
    "watchUrl": "https://www.youtube.com/watch?v=sIn5i3QemAY",
    "poster": "https://img.youtube.com/vi/sIn5i3QemAY/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/sIn5i3QemAY/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/sIn5i3QemAY/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.7,
    "genre": [
      "Romance"
    ],
    "duration": "1h 18m",
    "durationMinutes": 78,
    "durationRaw": "78 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Maurice Sam",
      "Chioma Nwaoha",
      "Sonia Uche"
    ],
    "synopsis": "Caught between two lovers, she must choose between passion and stability.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Felix Okeke Movies TV",
    "channel": "Felix Okeke Movies TV",
    "source": "YouTube",
    "views": "1.2M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "maurice-sam"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 37,
    "title": "Mr & Mrs Trouble - Ekene Umenwa, Onny Michael",
    "slug": "mr-mrs-trouble-ekene-umenwa-onny-michael",
    "youtubeId": "j1-L2_ygw2I",
    "youtubeUrl": "https://www.youtube.com/watch?v=j1-L2_ygw2I",
    "watchUrl": "https://www.youtube.com/watch?v=j1-L2_ygw2I",
    "poster": "https://img.youtube.com/vi/j1-L2_ygw2I/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/j1-L2_ygw2I/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/j1-L2_ygw2I/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.5,
    "genre": [
      "Comedy Drama",
      "Faith"
    ],
    "duration": "2h 7m",
    "durationMinutes": 127,
    "durationRaw": "127 min",
    "language": "English",
    "director": "Uche Nancy",
    "cast": [
      "Ekene Umenwa",
      "Onny Michael"
    ],
    "synopsis": "Trouble follows this chaotic couple everywhere, but love keeps them together.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Urban Nolly TV",
    "channel": "Urban Nolly TV",
    "source": "YouTube",
    "views": "1.2M views",
    "tags": [
      "nollywood",
      "comedy drama",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "ekene-umenwa"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 38,
    "title": "Ghetto Affection - Regina Daniels, Eso Dike",
    "slug": "ghetto-affection-regina-daniels-eso-dike",
    "youtubeId": "D-K6nGmliFU",
    "youtubeUrl": "https://www.youtube.com/watch?v=D-K6nGmliFU",
    "watchUrl": "https://www.youtube.com/watch?v=D-K6nGmliFU",
    "poster": "https://img.youtube.com/vi/D-K6nGmliFU/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/D-K6nGmliFU/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/D-K6nGmliFU/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 6.9,
    "genre": [
      "Drama",
      "Royal"
    ],
    "duration": "2h 7m",
    "durationMinutes": 127,
    "durationRaw": "127 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Regina Daniels",
      "Eso Dike"
    ],
    "synopsis": "A ghetto love story about affection, betrayal and survival in the trenches.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Mercy Johnson TV",
    "channel": "Mercy Johnson TV",
    "source": "YouTube",
    "views": "3.1M views",
    "tags": [
      "nollywood",
      "drama",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "regina-daniels"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 39,
    "title": "My Tomboy Sister - Regina Daniels, Mike Ezuruonye",
    "slug": "my-tomboy-sister-regina-daniels-mike-ezuruonye",
    "youtubeId": "0JTmoKQVXrw",
    "youtubeUrl": "https://www.youtube.com/watch?v=0JTmoKQVXrw",
    "watchUrl": "https://www.youtube.com/watch?v=0JTmoKQVXrw",
    "poster": "https://img.youtube.com/vi/0JTmoKQVXrw/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/0JTmoKQVXrw/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/0JTmoKQVXrw/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 8.4,
    "genre": [
      "Family Drama",
      "Horror"
    ],
    "duration": "2h 15m",
    "durationMinutes": 135,
    "durationRaw": "135 min",
    "language": "English",
    "director": "Omoni Oboli",
    "cast": [
      "Regina Daniels",
      "Mike Ezuruonye"
    ],
    "synopsis": "A tomboy sister challenges family traditions and finds love where she least expects.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Mercy Johnson TV",
    "channel": "Mercy Johnson TV",
    "source": "YouTube",
    "views": "1.5M views",
    "tags": [
      "nollywood",
      "family drama",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "regina-daniels"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 40,
    "title": "Ijeanuri - Faith Duke, Chibuike Darlington, Malik Milton",
    "slug": "ijeanuri-faith-duke-chibuike-darlington-malik-milton",
    "youtubeId": "_lW7lAFaFL4",
    "youtubeUrl": "https://www.youtube.com/watch?v=_lW7lAFaFL4",
    "watchUrl": "https://www.youtube.com/watch?v=_lW7lAFaFL4",
    "poster": "https://img.youtube.com/vi/_lW7lAFaFL4/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/_lW7lAFaFL4/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/_lW7lAFaFL4/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 7.5,
    "genre": [
      "Epic"
    ],
    "duration": "1h 18m",
    "durationMinutes": 78,
    "durationRaw": "78 min",
    "language": "English, Igbo",
    "director": "Emem Isong",
    "cast": [
      "Faith Duke",
      "Chibuike Darlington",
      "Malik Milton"
    ],
    "synopsis": "An epic tale of destiny, love and spiritual battles in an ancient kingdom.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Mercy Johnson TV",
    "channel": "Mercy Johnson TV",
    "source": "YouTube",
    "views": "6.8M views",
    "tags": [
      "nollywood",
      "epic",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "faith-duke"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 41,
    "title": "Real Lovers - Chinenye Nnebe, Maurice Sam",
    "slug": "real-lovers-chinenye-nnebe-maurice-sam",
    "youtubeId": "OzPxgXo6bi0",
    "youtubeUrl": "https://www.youtube.com/watch?v=OzPxgXo6bi0",
    "watchUrl": "https://www.youtube.com/watch?v=OzPxgXo6bi0",
    "poster": "https://img.youtube.com/vi/OzPxgXo6bi0/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/OzPxgXo6bi0/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/OzPxgXo6bi0/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.3,
    "genre": [
      "Romance"
    ],
    "duration": "2h 22m",
    "durationMinutes": 142,
    "durationRaw": "142 min",
    "language": "English",
    "director": "Uche Nancy",
    "cast": [
      "Chinenye Nnebe",
      "Maurice Sam"
    ],
    "synopsis": "She asked her friend to find her true love before she dies, but friendship turns to exploitation.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Omoni Oboli TV",
    "channel": "Omoni Oboli TV",
    "source": "YouTube",
    "views": "9.1M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "chinenye-nnebe"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 42,
    "title": "The Boy For Me - Chinenye Nnebe, Clinton Joshua",
    "slug": "the-boy-for-me-chinenye-nnebe-clinton-joshua",
    "youtubeId": "H1SZWLkySYo",
    "youtubeUrl": "https://www.youtube.com/watch?v=H1SZWLkySYo",
    "watchUrl": "https://www.youtube.com/watch?v=H1SZWLkySYo",
    "poster": "https://img.youtube.com/vi/H1SZWLkySYo/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/H1SZWLkySYo/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/H1SZWLkySYo/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.8,
    "genre": [
      "Romance"
    ],
    "duration": "1h 38m",
    "durationMinutes": 98,
    "durationRaw": "98 min",
    "language": "English",
    "director": "Uche Nancy",
    "cast": [
      "Chinenye Nnebe",
      "Clinton Joshua"
    ],
    "synopsis": "A young woman searches for the perfect boy, but love comes from the most unexpected place.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Felix Okeke Movies TV",
    "channel": "Felix Okeke Movies TV",
    "source": "YouTube",
    "views": "9.1M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "chinenye-nnebe"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 43,
    "title": "Rented Wife - Chinenye Nnebe, Peter Komba, Nana Addae",
    "slug": "rented-wife-chinenye-nnebe-peter-komba-nana-addae",
    "youtubeId": "3t9QKRByARc",
    "youtubeUrl": "https://www.youtube.com/watch?v=3t9QKRByARc",
    "watchUrl": "https://www.youtube.com/watch?v=3t9QKRByARc",
    "poster": "https://img.youtube.com/vi/3t9QKRByARc/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/3t9QKRByARc/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/3t9QKRByARc/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.0,
    "genre": [
      "Drama"
    ],
    "duration": "1h 41m",
    "durationMinutes": 101,
    "durationRaw": "101 min",
    "language": "English",
    "director": "Lancelot Oduwa Imasuen",
    "cast": [
      "Chinenye Nnebe",
      "Peter Komba",
      "Nana Addae"
    ],
    "synopsis": "A man rents a wife to impress his family, but the fake marriage starts to feel too real.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Nollywood TV",
    "channel": "Nollywood TV",
    "source": "YouTube",
    "views": "1.5M views",
    "tags": [
      "nollywood",
      "drama",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "chinenye-nnebe"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 44,
    "title": "Love On Trial - Deza The Great, Chinenye Nnebe",
    "slug": "love-on-trial-deza-the-great-chinenye-nnebe",
    "youtubeId": "h_rAC4HVjyU",
    "youtubeUrl": "https://www.youtube.com/watch?v=h_rAC4HVjyU",
    "watchUrl": "https://www.youtube.com/watch?v=h_rAC4HVjyU",
    "poster": "https://img.youtube.com/vi/h_rAC4HVjyU/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/h_rAC4HVjyU/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/h_rAC4HVjyU/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.4,
    "genre": [
      "Romantic Drama"
    ],
    "duration": "1h 32m",
    "durationMinutes": 92,
    "durationRaw": "92 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Deza The Great",
      "Chinenye Nnebe"
    ],
    "synopsis": "An estranged couple in divorce proceedings rediscover love when sparks fly during out-of-court settlement.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Emem Isong TV",
    "channel": "Emem Isong TV",
    "source": "YouTube",
    "views": "3.1M views",
    "tags": [
      "nollywood",
      "romantic drama",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "deza-the-great"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 45,
    "title": "Homeless Lovers - Frederick Leonard, Chinenye Nnebe",
    "slug": "homeless-lovers-frederick-leonard-chinenye-nnebe",
    "youtubeId": "DCyqewmk9ZE",
    "youtubeUrl": "https://www.youtube.com/watch?v=DCyqewmk9ZE",
    "watchUrl": "https://www.youtube.com/watch?v=DCyqewmk9ZE",
    "poster": "https://img.youtube.com/vi/DCyqewmk9ZE/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/DCyqewmk9ZE/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/DCyqewmk9ZE/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.7,
    "genre": [
      "Romance"
    ],
    "duration": "2h 2m",
    "durationMinutes": 122,
    "durationRaw": "122 min",
    "language": "English",
    "director": "Uche Nancy",
    "cast": [
      "Frederick Leonard",
      "Chinenye Nnebe"
    ],
    "synopsis": "Two homeless lovers find hope and love despite the odds stacked against them.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Uche Nancy TV",
    "channel": "Uche Nancy TV",
    "source": "YouTube",
    "views": "9.1M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "frederick-leonard"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 46,
    "title": "Trust On Trial - Pamela Okoye, Clinton Joshua, Chioma Edak",
    "slug": "trust-on-trial-pamela-okoye-clinton-joshua-chioma-edak",
    "youtubeId": "wz7vLgxXJL8",
    "youtubeUrl": "https://www.youtube.com/watch?v=wz7vLgxXJL8",
    "watchUrl": "https://www.youtube.com/watch?v=wz7vLgxXJL8",
    "poster": "https://img.youtube.com/vi/wz7vLgxXJL8/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/wz7vLgxXJL8/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/wz7vLgxXJL8/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 7.6,
    "genre": [
      "Courtroom Drama"
    ],
    "duration": "1h 38m",
    "durationMinutes": 98,
    "durationRaw": "98 min",
    "language": "English",
    "director": "Ruth Kadiri",
    "cast": [
      "Clinton Joshua",
      "Pamela Okoye",
      "Chioma Edak"
    ],
    "synopsis": "Trust itself is on trial when love, betrayal and suspense keep you guessing until the very end.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Pamela Okoye TV",
    "channel": "Pamela Okoye TV",
    "source": "YouTube",
    "views": "5.2M views",
    "tags": [
      "nollywood",
      "courtroom drama",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "clinton-joshua"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 47,
    "title": "Accidentally Us - Clinton Joshua, Omeche Oko, Sandra Osei",
    "slug": "accidentally-us-clinton-joshua-omeche-oko-sandra-osei",
    "youtubeId": "Z8r4Kai3b1U",
    "youtubeUrl": "https://www.youtube.com/watch?v=Z8r4Kai3b1U",
    "watchUrl": "https://www.youtube.com/watch?v=Z8r4Kai3b1U",
    "poster": "https://img.youtube.com/vi/Z8r4Kai3b1U/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/Z8r4Kai3b1U/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/Z8r4Kai3b1U/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 6.9,
    "genre": [
      "Romance"
    ],
    "duration": "1h 24m",
    "durationMinutes": 84,
    "durationRaw": "84 min",
    "language": "English",
    "director": "Omoni Oboli",
    "cast": [
      "Clinton Joshua",
      "Omeche Oko",
      "Sandra Osei-Nti"
    ],
    "synopsis": "An accidental encounter leads to a love story that neither of them planned for.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Nollywood African Movies",
    "channel": "Nollywood African Movies",
    "source": "YouTube",
    "views": "4.5M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "clinton-joshua"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 48,
    "title": "My Version Of Love - Clinton Joshua, Sophia Chisom",
    "slug": "my-version-of-love-clinton-joshua-sophia-chisom",
    "youtubeId": "m_-NZgknnGY",
    "youtubeUrl": "https://www.youtube.com/watch?v=m_-NZgknnGY",
    "watchUrl": "https://www.youtube.com/watch?v=m_-NZgknnGY",
    "poster": "https://img.youtube.com/vi/m_-NZgknnGY/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/m_-NZgknnGY/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/m_-NZgknnGY/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 6.9,
    "genre": [
      "Romance"
    ],
    "duration": "1h 18m",
    "durationMinutes": 78,
    "durationRaw": "78 min",
    "language": "English",
    "director": "Moses Inwang",
    "cast": [
      "Clinton Joshua",
      "Sophia Chisom"
    ],
    "synopsis": "A heartfelt and emotional journey about what love truly means to two different souls.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Uche Nancy TV",
    "channel": "Uche Nancy TV",
    "source": "YouTube",
    "views": "4.5M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "clinton-joshua"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 49,
    "title": "In Love With A Bread Winner - Chioma Nwaoha, Clinton Joshua",
    "slug": "in-love-with-a-bread-winner-chioma-nwaoha-clinton-joshua",
    "youtubeId": "LbJ5Pt5XMFU",
    "youtubeUrl": "https://www.youtube.com/watch?v=LbJ5Pt5XMFU",
    "watchUrl": "https://www.youtube.com/watch?v=LbJ5Pt5XMFU",
    "poster": "https://img.youtube.com/vi/LbJ5Pt5XMFU/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/LbJ5Pt5XMFU/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/LbJ5Pt5XMFU/maxresdefault.jpg",
    "year": 2026,
    "marketingYear": 2026,
    "rating": 7.4,
    "genre": [
      "Romance"
    ],
    "duration": "2h 15m",
    "durationMinutes": 135,
    "durationRaw": "135 min",
    "language": "English",
    "director": "Omoni Oboli",
    "cast": [
      "Chioma Nwaoha",
      "Clinton Joshua"
    ],
    "synopsis": "She falls for the family's breadwinner, but love is tested by family pressure and poverty.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Naija Plus TV",
    "channel": "Naija Plus TV",
    "source": "YouTube",
    "views": "1.2M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2026",
      "full movie",
      "african cinema",
      "chioma-nwaoha"
    ],
    "isUpToDate": true,
    "working": true
  },
  {
    "id": 50,
    "title": "Deep In Love - Clinton Joshua, Chioma Nwaoha",
    "slug": "deep-in-love-clinton-joshua-chioma-nwaoha",
    "youtubeId": "5FFKPtsEVP4",
    "youtubeUrl": "https://www.youtube.com/watch?v=5FFKPtsEVP4",
    "watchUrl": "https://www.youtube.com/watch?v=5FFKPtsEVP4",
    "poster": "https://img.youtube.com/vi/5FFKPtsEVP4/mqdefault.jpg",
    "posterHigh": "https://img.youtube.com/vi/5FFKPtsEVP4/hqdefault.jpg",
    "posterMax": "https://img.youtube.com/vi/5FFKPtsEVP4/maxresdefault.jpg",
    "year": 2025,
    "marketingYear": 2025,
    "rating": 8.8,
    "genre": [
      "Romance",
      "Adventure"
    ],
    "duration": "1h 58m",
    "durationMinutes": 118,
    "durationRaw": "118 min",
    "language": "English",
    "director": "Emem Isong",
    "cast": [
      "Clinton Joshua",
      "Chioma Nwaoha"
    ],
    "synopsis": "Deeply in love, a couple must overcome class, family and past mistakes to stay together.",
    "isFeatured": false,
    "verifiedReal": true,
    "hasTrailer": false,
    "sourceChannel": "Nolly9ja TV",
    "channel": "Nolly9ja TV",
    "source": "YouTube",
    "views": "1.5M views",
    "tags": [
      "nollywood",
      "romance",
      "nigerian movie",
      "2025",
      "full movie",
      "african cinema",
      "clinton-joshua"
    ],
    "isUpToDate": true,
    "working": true
  }
];